---
title: "STAT 230A Final Project Code"
author: "Andrew Du"
date: "`r Sys.Date()`"
output: pdf_document
---

```{r setup, include=FALSE}
library(foreign)
library(knitr)
library(kableExtra)
library(sandwich)
library(haven)
library(lmtest)
library(MASS)
library(mfx)
library(prediction)
library(assertthat)
library(xtable)
library(lfe)
knitr::opts_chunk$set(echo = TRUE)
```

```{r, include=FALSE}
setwd('/Users/du/Documents/sp24/stat230a/final_project/wfh')
install.packages("/Users/du/Documents/sp24/stat230a/final_project/wfh/prediction_0.3.17.tar.gz", type = "source", repos = NULL)
install.packages("/Users/du/Documents/sp24/stat230a/final_project/wfh/margins_0.3.26.1.tar.gz", type = "source", repos = NULL)
library(prediction)
library(margins)
library(haven)
```

```{r}
library(devtools)
load_all("mfx")
```

### Probit Marginal Effects

#### Table 1

Redoing analyses from table 1, but with logit regression and robust standard error for all

Original table:

```{r table 1}
summary_volunteer_data <- read.dta("data/summary_volunteer.dta")
summary_volunteer_data$children <- ifelse(summary_volunteer_data$children == "yes", 1.0, 0.0)
summary_volunteer_data$bedroom <- ifelse(summary_volunteer_data$bedroom == "yes", 1.0, 0.0)
summary_volunteer_data
```

```{r}
table_1_formulas <- list(
  volunteer ~ children, 
  volunteer ~ married, 
  volunteer ~ children + married + commute + bedroom, 
  volunteer ~ children + married + commute + bedroom + high_educ + tenure,
  volunteer ~ children + married + commute + bedroom + high_educ + tenure + grosswage,
  volunteer ~ grosswage,
  volunteer ~ children + married + commute + bedroom + high_educ + tenure + grosswage + age + men
  )

table_1_regressors <- c("age", "tenure", "grosswage", "children", "bedroom", "commute", "men", "married", "high_educ")
```

```{r}

compare_logit_probit_fit <- function(formula, data) {
  model_probit <- glm(formula, data=data, family=binomial(link="probit"))
  model_logit <- glm(formula, data=data, family=binomial(link="logit"))
  
  cat("probit model summary:", "\n")
  print(summary(model_probit))
  cat("logit model summary:", "\n")
  print(summary(model_logit))
}

compare_logit_probit <- function(formula, data, robust=FALSE, ehw_type="HC1", parse=FALSE, regressors=NULL) {
  model_probit <- probitmfx(formula, data=data, robust=robust, robust_type=ehw_type)
  model_logit <- logitmfx(formula, data=data, robust=robust, robust_type=ehw_type)
  
  if (robust) {
    cat("probit model average marginal effect with", ehw_type, "error:", "\n")
    print(model_probit$mfxest)
    cat("logit model average marginal effect with", ehw_type, "error:", "\n")
    print(model_logit$mfxest)
  } else {
    cat("probit model average marginal effect with standard error:", "\n")
    print(model_probit$mfxest)
    cat("logit model average marginal effect with standard error:", "\n")
    print(model_logit$mfxest)
  }
  
  if (parse && !is.null(regressors)) {
    results <- format_logit_probit_results(model_probit$mfxest, 
                                         model_logit$mfxest, 
                                         regressors)
    return(results)
  }
}

format_logit_probit_results <- function(mfxest_log, mfxest_prob, regressors) {
  df_mfxest_log <- data.frame(mfxest_log)
  df_mfxest_prob <- data.frame(mfxest_prob)
  
  formatted <- data.frame(Info = vector("character", length(regressors)),
                          row.names=regressors,
                          stringsAsFactors=FALSE)

  for (feat in regressors) {
    if (feat %in% rownames(df_mfxest_log)) {
      se_log <- df_mfxest_log[feat, "Std..Err."]
      se_prob <- df_mfxest_prob[feat, "Std..Err."]
      ame_log <- df_mfxest_log[feat, "dF.dx"]
      ame_prob <- df_mfxest_prob[feat, "dF.dx"]
      
      formatted[feat, "Info"] <- sprintf("$\\substack{%.3f / %.3f \\\\ (%.4f / %.4f)}$", 
                                ame_log, ame_prob, se_log, se_prob)
      
      } else {
        formatted[feat, "Info"] <- ""
      }
  }
  
  return(formatted)
}

parse_significance <- function(p_val) {
  significance <- ifelse(p_val < 0.01, "***",
                         ifelse(p_val < 0.05, "**",
                                ifelse(p_val < 0.1, "*", "")))
  return(significance)
}

format_hci_results <- function(mfxest_se, mfxest_hc0, mfxest_hc1, regressors) {
  df_mfxest_se <- data.frame(mfxest_se)
  df_mfxest_hc0 <- data.frame(mfxest_hc0)
  df_mfxest_hc1 <- data.frame(mfxest_hc1)
  
  formatted <- data.frame(Info = vector("character", length(regressors)),
                          row.names=regressors,
                          stringsAsFactors=FALSE)

  for (feat in regressors) {
    if (feat %in% rownames(df_mfxest_se)) {
      signif_se <- parse_significance(df_mfxest_se[feat, "P..z."])
      signif_hc0 <- parse_significance(df_mfxest_hc0[feat, "P..z."])
      signif_hc1 <- parse_significance(df_mfxest_hc1[feat, "P..z."])
      
      assert_that(signif_se == signif_hc0 && signif_se == signif_hc1, msg="significance values are not the same!")
      
      se <- df_mfxest_se[feat, "Std..Err."]
      hc0 <- df_mfxest_hc0[feat, "Std..Err."]
      hc1 <- df_mfxest_hc1[feat, "Std..Err."]
    
      ame <- df_mfxest_se[feat, "dF.dx"]
      
      formatted[feat, "Info"] <- sprintf("$\\substack{%.3f %s \\\\ (%.4f / %.4f / %.4f)}$", 
                                ame, signif_se, se, hc0, hc1)
      
      } else {
        formatted[feat, "Info"] <- ""
      }
  }
  
  return(formatted)
}

dprobit <- function(formula, 
                    data, 
                    parse=FALSE, 
                    regressors=NULL, 
                    robust=TRUE, 
                    robust_type="HC1") {
  model_probit <- probitmfx(formula, data=data, robust=robust, robust_type=robust_type)
  print(model_probit$mfxest)
  
  if (parse && !is.null(regressors)) {
    results <- format_dprobit_results(model_probit$mfxest, 
                                         regressors)
    return(results)
  }
}

format_dprobit_results <- function(mfxest, regressors) {
  df_mfxest <- data.frame(mfxest)
  
  formatted <- data.frame(Info = vector("character", length(regressors)),
                          row.names=regressors,
                          stringsAsFactors=FALSE)

  for (feat in regressors) {
    if (feat %in% rownames(df_mfxest)) {
      signif <- parse_significance(df_mfxest[feat, "P..z."])
      
      se <- df_mfxest[feat, "Std..Err."]
      ame <- df_mfxest[feat, "dF.dx"]
      
      formatted[feat, "Info"] <- sprintf("$\\substack{ %.3f %s \\\\ (%.4f) }$", 
                                ame, signif, se)
      
      } else {
        formatted[feat, "Info"] <- ""
      }
  }
  
  return(formatted)
}

compare_hci_errors <- function(formula, data, parse=FALSE, regressors=NULL) {
  model_probit_se <- probitmfx(formula, data=data, robust=FALSE)
  model_probit_hc0 <- probitmfx(formula, data=data, robust=TRUE, robust_type="HC0")
  model_probit_hc1 <- probitmfx(formula, data=data, robust=TRUE, robust_type="HC1")
  
  cat("probit model with standard errors:", "\n")
  print(model_probit_se$mfxest)
  cat("probit model with hc0 correction:", "\n")
  print(model_probit_hc0$mfxest)
  cat("probit model with hc1 correction:", "\n")
  print(model_probit_hc1$mfxest)
  
  if (parse && !is.null(regressors)) {
    results <- format_hci_results(model_probit_se$mfxest, 
                                         model_probit_hc0$mfxest, 
                                         model_probit_hc1$mfxest,
                                         regressors)
    return(results)
  }
}
```

```{r}
child_reg <- glm(children ~ married + bedroom - 1, data=summary_volunteer_data, family=binomial(link="probit"))
summary(child_reg)

cor(summary_volunteer_data$married, summary_volunteer_data$bedroom)
cor(summary_volunteer_data$married, summary_volunteer_data$children)
cor(summary_volunteer_data$bedroom, summary_volunteer_data$children)
```

```{r}
other_formula <- married ~ bedroom
compare_hci_errors(other_formula, data=summary_volunteer_data)
```

```{r}
#other_formula <- volunteer ~ children + married + commute + bedroom
other_formula <- volunteer ~ married + commute
compare_hci_errors(other_formula, data=summary_volunteer_data)
```

Make table 1

```{r}
df_table <- data.frame(row.names=table_1_regressors)
for (f in table_1_formulas) {
  #compare_hci_errors(f, data=summary_volunteer_data, 
  #                   parse=TRUE, 
  #                   regressors=table_1_regressors)
  col <- compare_hci_errors(f, data=summary_volunteer_data, parse=TRUE, 
                     regressors=table_1_regressors)
  df_table <- cbind(df_table, col)
  #print(compare_hci_errors(f, data=summary_volunteer_data, parse=TRUE, 
  #                   regressors=table_1_regressors))
  #cat("\n")
}
colnames(df_table) <- paste0("(", seq_along(df_table), ")")
latex_table <- xtable(df_table)
print(latex_table, type="latex", sanitize.text.function = function(x) {x}, tabular.environment = "longtable")
cat("\n")
print(df_table)
```

Generate dprobit versus dlogit:

```{r}
df_table <- data.frame(row.names=table_1_regressors)
for (f in table_1_formulas) {
  #compare_hci_errors(f, data=summary_volunteer_data, 
  #                   parse=TRUE, 
  #                   regressors=table_1_regressors)
  col <- compare_logit_probit(f, data=summary_volunteer_data, 
                              robust=TRUE, 
                              ehw_type="HC1", 
                              parse=TRUE, 
                              regressors=table_1_regressors)
  df_table <- cbind(df_table, col)
  #print(compare_hci_errors(f, data=summary_volunteer_data, parse=TRUE, 
  #                   regressors=table_1_regressors))
  #cat("\n")
}
colnames(df_table) <- paste0("(", seq_along(df_table), ")")
latex_table_row1 <- xtable(df_table[, c("(1)", "(2)", "(3)", "(4)")])
latex_table_row2 <- xtable(df_table[, c("(5)", "(6)", "(7)")])
print(latex_table_row1, type="latex", sanitize.text.function = function(x) {x}, tabular.environment="tabularx")
print(latex_table_row2, type="latex", sanitize.text.function = function(x) {x}, tabular.environment="tabularx")
#latex_table <- xtable(df_table)
#print(latex_table, type="latex", sanitize.text.function = function(x) {x}, tabular.environment = "tabularx")
# cat("\n")
print(subset(df_table[, c("(1)", "(2)", "(3)")]))
```

#### Table 6

```{r}
switch_return_data <- read.dta("data/switch_return.dta")
switch_return_data
switch_return_data$performance_dif <- switch_return_data$perform11 
                                    - switch_return_data$perform10
switch_home_data <- read.dta("data/switch_gohome.dta")
switch_home_data
switch_home_data$performance_dif <- switch_home_data$perform11 
                                    - switch_home_data$perform10
colnames(switch_home_data)
```

```{r}
table_6a_formulas <- c(
  return ~ perform11,
  return ~ perform10,
  return ~ perform11 + perform10,
  return ~ perform11 + perform10 + married + livewparents + costofcommute,
  return ~ performance_dif,
  return ~ performance_dif + married + livewparents + costofcommute
)

table_6b_formulas <- c(
  join ~ perform11,
  join ~ perform10,
  join ~ perform11 + perform10,
  join ~ performance_dif,
  join ~ perform11 + perform10 + married + livewparents + costofcommute
)

table_6_regressors <- c(
  "perform11",
  "perform10",
  "performance_dif",
  "married",
  "livewparents",
  "costofcommute"
)
```

```{r}
df_table <- data.frame(row.names=table_6_regressors)
for (f in table_6a_formulas) {
  df_table <- cbind(df_table, dprobit(f, data=switch_return_data, robust=TRUE, parse=TRUE, regressors=table_6_regressors))
  cat("\n")
}
colnames(df_table) <- paste0("(", seq_along(df_table), ")")
latex_table <- xtable(df_table)
print(latex_table, type="latex", sanitize.text.function = function(x) {x})
cat("\n")
print(df_table)
```

### Fixed Effects Regressions

```{r}
exper_perf_data <- read_dta("data/performance_during_exper.dta")
exper_perf_data$during_experiment <- as.integer(exper_perf_data$year_week >= 201049)
exper_perf_data$experiment_treatment_during <- exper_perf_data$during_experiment * exper_perf_data$experiment_treatment
exper_perf_data
```

```{r}
table_2_targets <- c(
  "perform1"
)
table_2_regressors <- c(
  c("experiment_treatment", "year_week", "personid")
)
```

```{r}
cols_used <- c(table_2_regressors[1], table_2_targets[1])
table_2_regressors[1]
cols_used
```

```{r}

col_1_regression <-  felm(perform1 ~ experiment_treatment *  + experiment_control + as.factor(year_week)
                          | personid | 0 | personid, 
                          data=exper_perf_data, 
                          subset=(year_week != 201049 & (expgroup == 1 | expgroup == 0)))
summary(col_1_regression)

col_1_regression_absorb_time <-  felm(perform1 ~ experiment_treatment + experiment_control
                          | personid + year_week | 0 | personid, 
                          data=exper_perf_data, 
                          subset=(year_week != 201049 & (expgroup == 1 | expgroup == 0)))
summary(col_1_regression_absorb_time)

yw_cluster_regression <-  felm(perform1 ~ experiment_treatment + as.factor(year_week)
                          | personid | 0 | year_week + experiment_treatment, 
                          data=exper_perf_data, 
                          subset=(year_week != 201049 & (expgroup == 1 | expgroup == 0)))
summary(yw_cluster_regression)

```

Table 4

```{r}
colnames(exper_perf_data)
#exper_perf_data$experiment_control <- as.integer(exper_perf_data$expgroup == 0)
#exper_perf_data$experiment_treatment <- as.integer(exper_perf_data$expgroup == 1 & exper_perf_data$year_week >= 201049)
#exper_perf_data$experiment_nantong <- as.integer(exper_perf_data$expgroup == 3)
exper_perf_data
```

```{r}
col_1_regression <-  felm(perform1 ~ experiment_treatment_during
                          + experiment_control 
                          + as.factor(year_week)
                          | personid | 0 | personid, 
                          data=exper_perf_data, 
                          subset=(year_week != 201049 & (expgroup != 2)))
summary(col_1_regression)
```
